// Local browser QA against disposable test servers. OTP is supplied by the local mock-mail fixture only.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');const {chromium}=require('playwright');
const store=process.env.TINY_TALE_QA_STORE||'http://127.0.0.1:5300',admin=process.env.TINY_TALE_QA_ADMIN||'http://127.0.0.1:5301',out=process.env.TINY_TALE_QA_OUTPUT||'/tmp/tiny-v6-preview';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader'],headless:true});const ctx=await browser.newContext({viewport:{width:1365,height:1000}});const page=await ctx.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(store);await page.waitForSelector('#products .card');await page.waitForSelector('#pauseHighlights');assert.equal(await page.locator('#products .card').count(),11);assert(await page.locator('#resultCount').textContent());
 await page.screenshot({path:path.join(out,'Customer-desktop.png')});await page.click('#pauseHighlights');assert(await page.locator('.offer-ticker').evaluate(e=>e.classList.contains('paused')));
 await page.selectOption('#priceLimit','200');assert(await page.locator('#products .card').count()<11);await page.click('#clearFilters');assert.equal(await page.locator('#products .card').count(),11);
 await page.locator('[data-view]').first().click();await page.waitForSelector('#detail[open]');await page.fill('#productDeliveryForm [name=pin]','638052');await page.click('#productDeliveryForm button');await page.waitForFunction(()=>document.querySelector('#productDeliveryResult').textContent.includes('Estimated delivery'));
 await page.locator('#detail [data-add]').click();await page.click('#detail [data-close]');assert.equal(await page.locator('#recentCards .recent-card').count(),1);await page.click('#cartButton');await page.waitForSelector('#shippingProgress:not(.hidden)');assert((await page.locator('#shippingProgress').textContent()).includes('free delivery'));
 // The existing email OTP and shopping continuation must still work with the new layout.
 await page.click('#checkoutButton');await page.waitForSelector('#loginDialog[open]');await page.fill('#loginEmail','browser-qa@example.test');await page.click('#sendCode');await page.waitForSelector('#otpForm:not(.hidden)');
 if(process.env.TINY_TALE_QA_OTP_FILE){const otp=JSON.parse(fs.readFileSync(process.env.TINY_TALE_QA_OTP_FILE));await page.fill('#otpCode',otp.code);await page.click('#verifyCode');await page.waitForSelector('#checkout[open]');const f=page.locator('#checkoutForm');for(const [name,value] of Object.entries({name:'Local browser tester',phone:'9876543210',address:'QA address',city:'Erode',state:'Tamil Nadu',pin:'638052'}))await f.locator(`[name=${name}]`).fill(value);await page.click('#reviewPayment');await page.selectOption('#paymentMethod','upi');await page.fill('#upiId','demo@tinytest');await page.waitForSelector('#qrHolder img');await page.click('#placeOrder');await page.waitForSelector('#orderSuccess:not(.hidden)');assert((await page.locator('#orderSuccess').textContent()).includes('Order number:'));await page.click('#checkout [data-close]');}
 // Desktop and phone overflow plus reduced-motion behaviour.
 await page.setViewportSize({width:390,height:844});await page.goto(store);await page.waitForSelector('#products .card');await page.screenshot({path:path.join(out,'Customer-mobile.png')});if(!await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&!e.closest('.ticker-window')&&!e.closest('dialog')).map(e=>({tag:e.tagName,id:e.id,class:e.className,right:e.getBoundingClientRect().right})).slice(0,20)));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.ticker-track').evaluate(e=>getComputedStyle(e).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
 const studio=await ctx.newPage();studio.on('pageerror',e=>errors.push(e.message));await studio.goto(admin);await studio.fill('#password',process.env.TINY_TALE_QA_OWNER_PASSWORD||'local-owner-password');await studio.click('#loginForm button');await studio.waitForSelector('#app:not(.hidden)');await studio.waitForFunction(()=>!document.querySelector('#content').hasAttribute('aria-busy'));await studio.locator('#content').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished.catch(()=>{}))));await studio.screenshot({path:path.join(out,'Admin-desktop.png')});
 await studio.click('[data-tab=appearance]');await studio.waitForSelector('#appearanceForm');await studio.locator('[data-highlight-text]').first().fill('Knot Jabla weekend offer');await studio.click('#saveAppearance');await studio.waitForFunction(()=>document.querySelector('#toast').textContent==='Scrolling strip published');await page.reload();await page.waitForFunction(()=>document.querySelector('.offer-ticker').textContent.includes('Knot Jabla weekend offer'));
 await studio.click('[data-tab=banners]');await studio.waitForSelector('#newBanner');await studio.click('#newBanner');await studio.setInputFiles('#bannerFile',path.join(__dirname,'../static/images/product-1.png'));await studio.fill('[name=title]','Knot Jabla offer');await studio.selectOption('#bannerDestination','custom');await studio.fill('#customBannerLink','/?product=2#collection');await studio.fill('#bannerButtonLabel input','Explore Knot Jabla');await studio.click('#saveBanner');await studio.waitForFunction(()=>document.querySelector('#toast').textContent==='Banner published');
 await studio.click('[data-tab=media]');await studio.waitForSelector('#mediaProduct');await studio.selectOption('#mediaProduct','2');await studio.waitForSelector('#galleryFiles');await studio.setInputFiles('#galleryFiles',[path.join(__dirname,'../static/images/product-0.png'),path.join(__dirname,'../static/images/product-2.png')]);await studio.waitForFunction(()=>document.querySelectorAll('#galleryList>div').length===2);await studio.click('#saveMerch');await studio.waitForFunction(()=>document.querySelector('#toast').textContent==='Gallery and details published');
 await page.reload();await page.waitForSelector('#offerBanners a.button');await page.locator('#offerBanners a.button').click();await page.waitForSelector('#detail[open]');assert((await page.locator('#detail h2').textContent()).includes('Knot Jabla'));assert.equal(await page.locator('[data-gallery-index]').count(),3);await page.click('#galleryNext');await page.waitForFunction(()=>{const g=document.querySelector('#detailGallery');return Math.abs(g.scrollLeft-(g.children[1].offsetLeft-g.children[0].offsetLeft))<2&&document.querySelector('#galleryPosition').textContent.startsWith('2')});await page.click('[data-gallery-index="2"]');await page.waitForFunction(()=>{const g=document.querySelector('#detailGallery');return Math.abs(g.scrollLeft-(g.children[2].offsetLeft-g.children[0].offsetLeft))<2&&document.querySelector('#galleryPosition').textContent.startsWith('3')});await page.locator('#detail').evaluate(el=>el.scrollTop=0);await page.screenshot({path:path.join(out,'Product-gallery-mobile.png')});await page.click('#detail [data-close]');
 await studio.click('[data-tab=reports]');await studio.waitForSelector('#reportForm');await studio.click('#generateReport');await studio.waitForSelector('#reportResult iframe');assert.equal(await studio.locator('#reportResult a[download]').count(),2);
 await studio.evaluate(()=>{document.querySelector('[data-tab=email]').click();document.querySelector('[data-tab=appearance]').click();document.querySelector('[data-tab=products]').click()});await studio.waitForFunction(()=>document.querySelector('#content').dataset.view==='products'&&!document.querySelector('#content').hasAttribute('aria-busy'));assert((await studio.locator('#title').textContent()).includes('Products'));
 await studio.setViewportSize({width:390,height:844});await studio.click('#adminNavToggle');await studio.click('[data-tab=products]');await studio.waitForSelector('[data-edit]');assert(await studio.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await studio.waitForFunction(()=>!document.querySelector('#content').hasAttribute('aria-busy'));await studio.locator('#content').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished.catch(()=>{}))));await studio.screenshot({path:path.join(out,'Admin-mobile.png')});
 const keeperContext=await browser.newContext({viewport:{width:1365,height:1000}});const keeper=await keeperContext.newPage();keeper.on('pageerror',e=>errors.push(e.message));await keeper.goto(admin);await keeper.fill('#username','keeper');await keeper.fill('#password','local-keeper-password');await keeper.click('#loginForm button');await keeper.waitForSelector('#app:not(.hidden)');await keeper.waitForSelector('[data-edit]');assert.equal(await keeper.locator('[data-tab]:visible').count(),2);assert.equal(await keeper.locator('[data-tab=appearance]:visible').count(),0);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS browser: real desktop/mobile layouts, no document overflow or JavaScript errors, filter/reset, recently viewed, product PIN estimate, bag shipping progress, mocked email OTP → UPI test order, editable strip, custom banner product navigation, PDF/Excel controls, store keeper navigation and reduced motion.');
})().catch(e=>{console.error(e);process.exit(1)});
